// @ts-check

import { readFileSync, writeFileSync, readdirSync } from "fs";
import path from "path";

// Adjust these if module folder structure changes
const inputDirPath = "./esm/";
const outputDirPath = "./cjs/";

const autoGeneratedNotice = [
  "// AUTOGENERATED .d.ts FILE. DO NOT EDIT BY HAND.",
  `// INSTEAD EDIT THE SOURCE IN ${path.join(inputDirPath, "*.d.ts")} file.`,
  "\n",
].join("\n");

// Copy .d.ts definitions into the cjs output folder. Prepend with notice that the file is
// autogenerated
for (const fileName of readdirSync(inputDirPath)) {
  if (/.d.ts$/.test(fileName)) {
    const text = readFileSync(path.join(inputDirPath, fileName), {
      encoding: "utf8",
    });

    const textWithNotice = autoGeneratedNotice + text;

    writeFileSync(path.join(outputDirPath, fileName), textWithNotice, {
      encoding: "utf8",
    });
  }
}
