// AUTOGENERATED .d.ts FILE. DO NOT EDIT BY HAND.
// INSTEAD EDIT THE SOURCE IN esm/*.d.ts file.

import type {Cloneable} from "./internal.js";

export function parse(str: string): Cloneable;
export function stringify(any: Cloneable): string;
